"""Frozen GitNext v1 rule identifiers in priority order."""

PR_RULES = {
    "MERGED": "PR_001_MERGED",
    "CLOSED": "PR_002_CLOSED_UNMERGED",
    "REPOSITORY_INACTIVE": "PR_003_REPOSITORY_INACTIVE",
    "DRAFT": "PR_004_DRAFT",
    "CONFLICT": "PR_005_BRANCH_CONFLICT",
    "CHECK_FAILURE": "PR_006_CHECK_FAILURE",
    "CHANGES_REQUESTED": "PR_007_CHANGES_REQUESTED",
    "UNRESOLVED_THREAD": "PR_008_UNRESOLVED_THREAD",
    "CHECK_PENDING": "PR_009_CHECK_PENDING",
    "REVIEW_REQUIRED": "PR_010_REVIEW_REQUIRED",
    "NO_AUTHOR_BLOCKER": "PR_011_NO_KNOWN_AUTHOR_BLOCKER",
    "FALLBACK": "PR_012_INSUFFICIENT_EVIDENCE",
}

ISSUE_RULES = {
    "CLOSED": "ISSUE_001_CLOSED",
    "REPOSITORY_INACTIVE": "ISSUE_002_REPOSITORY_INACTIVE",
    "DUPLICATE": "ISSUE_003_EXPLICIT_DUPLICATE",
    "LINKED_MERGED_PR": "ISSUE_004_LINKED_MERGED_PR",
    "NEEDS_INFO": "ISSUE_005_NEEDS_INFO",
    "OPEN_LINKED_PR": "ISSUE_006_OPEN_LINKED_PR",
    "FALLBACK": "ISSUE_007_INSUFFICIENT_EVIDENCE",
}
